### ISSUE TITLE
Clone the repo with -j8 option return an error

### ISSUE THREAD

**Issue by JekoTronik** [matthewgraybosch/oedipus-pelican-starter#3]
First of all, thank you for your starter kit, so helpful !!!

When trying to clone the repo, here is what I got : 

`$ git clone --recursive -j8 git://github.com/matthewgraybosch/oedipus-pelican-starter.git
error: unknown switch `j'`

Seems to work whithout the -j8 option. I did not find lot of info about this option neither... Maybe you could tell me about it ?

**Comment by matthewgraybosch** [comment]
The ```-j``` option probably controls how many processes ```git``` spawns to clone the repo. In any case, I've updated the README because the previous command line isn't appropriate for use by the general public.

Something like ```git clone --recursive https://github.com/matthewgraybosch/oedipus-pelican-starter.git``` is better because it doesn't require SSH access to the repository.

Thanks for filing this issue.
